version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      
    # For all packages, ignore all patch updates
    ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
