name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: anime-dl
            release_name: linux-x86_64
          - os: macos-latest
            artifact_name: anime-dl
            release_name: osx-x86_64
          - os: windows-latest
            artifact_name: anime-dl.exe
            release_name: win-x86_64.exe

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --locked
      
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        tag: ${{ github.ref }}
        asset_name: anime-dl-$tag-${{ matrix.release_name }}
