name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf
          - x86_64-pc-windows-msvc
          - x86_64-apple-darwin
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: target/x86_64-unknown-linux-musl/release/adl
            release_name: x86_64-unknown-linux-musl
            cross: false
            strip: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            artifact_name: target/armv7-unknown-linux-musleabihf/release/adl
            release_name: armv7-unknown-linux-musleabihf
            cross: true
            strip: false
          - os: ubuntu-latest
            target: arm-unknown-linux-musleabihf
            artifact_name: target/arm-unknown-linux-musleabihf/release/adl
            release_name: arm-unknown-linux-musleabihf
            cross: true
            strip: false
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: target/x86_64-apple-darwin/release/adl
            release_name: x86_64-apple-darwin
            cross: false
            strip: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: target/x86_64-pc-windows-msvc/release/adl.exe
            release_name: x86_64-pc-windows-msvc.exe
            cross: false
            strip: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          ci/ubuntu-install-packages

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }}
          use-cross: ${{ matrix.cross }}

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          tag: ${{ github.ref }}
          asset_name: anime-dl-$tag-${{ matrix.release_name }}
