name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Tests:
    name: ${{ matrix.os }} / Stable
    runs-on: ${{ matrix.os }}-latest
    strategy:
          matrix:
            os: [Ubuntu, MacOS, Windows]
  
    steps:
    - uses: actions/checkout@v2      
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test 
